In [51]:
import numpy as np

a = np.array([[1,2,3,4],[4,3,2,1]], float)
a

array([[1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [52]:
b = np.zeros((2,4), float)
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
b[0,:] = a[0,:]
b

array([[1., 2., 3., 4.],
       [0., 0., 0., 0.]])

In [54]:
b[1] = b[0]
b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [55]:
a

array([[1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [56]:
b[:,:] = 2.
b

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [57]:
b[:,1:] *= a[:,1:]
b

array([[2., 4., 6., 8.],
       [2., 6., 4., 2.]])